### ISSUE TITLE
PlayerBodyPart

### ISSUE THREAD

**Issue by curaai** [curaai/MyCraft#60]
- [ ] camera 움직임을 따라 머리 회전
- [ ] 카메라 -y 응시시 body cube 숨김
- [ ] 카메라에 right arm을 비춤

**Comment by curaai** [comment]
v1.2 마일스톤에선 skip
